import random
import string
import requests
from colorama import init, Fore
import webbrowser
import time

# Initialize Colorama
init()

# Masukkan URL webhook Anda di sini
DISCORD_WEBHOOK_URL = ""
OWNER_ROLE_ID = ""  # Ganti dengan ID role yang valid


def send_to_webhook(message, title="Nitro Code Generator", is_valid=False):
    """Kirim pesan ke Discord melalui webhook dalam format embed dengan menandai role jika valid."""
    if is_valid:
        message = f"<@&{OWNER_ROLE_ID}> {message}"  # Menandai role owner

    embed = {
        "embeds": [
            {
                "title": title,
                "description": message,
                "color": 3066993,  # Warna embed (light blue)
                "footer": {
                    "text": "Generated by Nitro Code Generator"
                }
            }
        ]
    }

    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json=embed, timeout=10)
        if response.status_code == 204:
            print(f"{Fore.GREEN}Berhasil mengirim webhook ke Discord.")
        else:
            print(f"{Fore.RED}Gagal mengirim webhook: {response.status_code}")
    except requests.RequestException as e:
        print(f"{Fore.RED}Error saat mengirim webhook: {e}")


def generate_code():
    """Generate a single Nitro gift code."""
    char_set = f"{string.ascii_uppercase}{string.digits}{string.ascii_lowercase}"
    return "".join(random.choices(char_set, k=16))


def verify_code(code):
    """Verify a generated Nitro code."""
    url = f"https://discordapp.com/api/v9/entitlements/gift-codes/{code}?with_application=false&with_subscription_plan=true"
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            return True
        return False
    except requests.RequestException:
        return False


def main():
    input("Tekan Enter jika Anda setuju, program akan dimulai\n")
    num = input('Masukkan jumlah kode yang akan di-generate: ')
    try:
        num = int(num)
        if num <= 0:
            raise ValueError("Jumlah harus lebih dari 0.")
    except ValueError as e:
        print(f"{Fore.RED}Input tidak valid: {e}")
        return

    with open("Nitro Codes.txt", "w", encoding='utf-8') as file:
        print(f'{Fore.BLUE}Tunggu, sedang membuat kode untuk Anda!')

        for i in range(num):
            code = generate_code()
            full_code = f"https://discord.gift/{code}"

            try:
                if verify_code(code):
                    log_message = f"{Fore.GREEN}Kode valid ditemukan: {full_code}"
                    print(log_message)
                    file.write(full_code + "\n")

                    # Kirim ke Discord melalui webhook (kode valid)
                    send_to_webhook(f"Kode Nitro valid ditemukan: {full_code}", title="Kode Nitro Valid", is_valid=True)

                    # Membuka kode valid di browser
                    webbrowser.open(full_code)
                else:
                    log_message = f"{Fore.RED}Kode tidak valid: {full_code}"
                    print(log_message)

                    # Kirim ke Discord melalui webhook (kode tidak valid)
                    send_to_webhook(f"Kode Nitro tidak valid: {full_code}", title="Kode Nitro Tidak Valid", is_valid=False)
            except Exception as e:
                print(f"{Fore.YELLOW}Error memverifikasi kode: {e}")

            # Delay opsional untuk menghindari spam API
            time.sleep(0.5)

    print(f'{Fore.CYAN}Berhasil menyelesaikan pembuatan! Kode valid ada di Nitro Codes.txt.')
    input("Tekan Enter untuk menutup!")


if __name__ == "__main__":
    main()
